mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

mail.username=shopverse.official2026@gmail.com
mail.password=vhblukjpmstiyzcm
app.base.url=http://localhost:8080/shopverse

jwt.secret=shopverse-secret-key-2026-super-secure-jwt-token
jwt.expiry=86400000