package entity.enums;

public enum OrderStatus {

    PENDING,
    CONFIRMED,
    PROCESSING,
    SHIPPED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED,
    RETURN_REQUESTED,
    REFUND_REQUESTED,
    REFUND_IN_PROGRESS,
    RETURNED,
    REFUNDED

}